language: ruby

rvm:
  - 2.6.5

cache: bundler

before_install:
  - gem install bundler -v '~> 2.0'

install:
  - bundle install --jobs=3 --retry=3

deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    tags: true
    branch: master
    ruby: '2.6.5'
