blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/welaika/wordmove/discussions/new?category=general
    about: Start an open discussion
  - name: Idea or feature request
    url: https://github.com/welaika/wordmove/discussions/new?category=ideas
    about: Propose your own ideas. We'll triage them and decide if bring them to the issue tracker
  - name: Help
    url: https://github.com/welaika/wordmove/discussions/new?category=q-a
    about: Ask for help if you're stuck with wordmove or integrating it with your workflow
